"use server";

import { createClient } from "@/lib/supabase/server";

export async function submitHack(challengeId: string, modelId: string, userPrompt: string) {
  const supabase = await createClient();
  
  // 1. Verify Authentication
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return { success: false, error: "Unauthorized access detected." };
  }

  // 2. Fetch the Challenge Details from Database
  const { data: challenge } = await supabase
    .from('challenges')
    .select('*')
    .eq('id', challengeId)
    .single();

  if (!challenge) {
    return { success: false, error: "Target system not found." };
  }

  let isWinner = false;
  let aiResponse = "";

  // 3. EVALUATION ENGINE (Branching Logic)
  if (challenge.is_bounty && challenge.endpoint_url) {
    // --- B2B BYOM PROXY ---
    try {
      // Set an 8-second timeout so bad company APIs don't hang our server
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 8000);

      const res = await fetch(challenge.endpoint_url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(challenge.auth_token ? { 'Authorization': `Bearer ${challenge.auth_token}` } : {})
        },
        body: JSON.stringify({
          hacker_id: user.id,
          prompt: userPrompt
        }),
        signal: controller.signal
      });

      clearTimeout(timeoutId);

      if (!res.ok) throw new Error("Target endpoint rejected connection.");

      const data = await res.json();
      
      // The strict B2B contract we force companies to follow:
      aiResponse = data.ai_response || "[No response generated by target]";
      isWinner = data.is_breached === true;

    } catch (error: any) {
      if (error.name === 'AbortError') {
         return { success: false, aiResponse: "CONNECTION TIMEOUT. Target API took longer than 8 seconds.", awardedPoints: 0, status: "FAILED" };
      }
      return { success: false, aiResponse: "CRITICAL FAILURE. Target endpoint is offline or malformed.", awardedPoints: 0, status: "FAILED" };
    }

  } else {
    // --- OFFICIAL MISSIONS (Local Evaluation) ---
    isWinner = userPrompt.toLowerCase().includes(challenge.flag_pattern.toLowerCase());
    if (isWinner) {
      aiResponse = `ERROR 0x4B2 in ${modelId}: Prompt injection successful. Security bypassed. '${challenge.flag_pattern}'`;
    } else {
      aiResponse = `[${modelId}] Access Denied. Security protocols holding. I cannot fulfill this request.`;
    }
  }

  // 4. PAYOUT & LOGGING (If they won)
  if (isWinner) {
    // Check if they already solved this specific model on this specific challenge
    const { data: existingSolve } = await supabase
      .from('solves')
      .select('id')
      .eq('user_id', user.id)
      .eq('challenge_id', challengeId)
      .eq('model_used', modelId)
      .single();

    if (!existingSolve) {
      // FIRST TIME SOLVE: Record the exploit and award points!
      await supabase.from('solves').insert({
        user_id: user.id,
        challenge_id: challengeId,
        model_used: modelId
      });

      // Fetch current points and update
      const { data: profile } = await supabase.from('profiles').select('points').eq('id', user.id).single();
      const newPoints = (profile?.points || 0) + challenge.points;
      
      await supabase.from('profiles').update({ points: newPoints }).eq('id', user.id);

      return { 
        success: true, 
        aiResponse, 
        awardedPoints: challenge.points, 
        status: "NEW_EXPLOIT" 
      };
    } else {
      // ALREADY SOLVED: They win the terminal, but get no duplicate points
      return { 
        success: true, 
        aiResponse, 
        awardedPoints: 0, 
        status: "ALREADY_EXPLOITED" 
      };
    }
  } else {
    // FAILED EXPLOIT
    return { success: false, aiResponse, awardedPoints: 0, status: "FAILED" };
  }
}